BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `word` (
	`word1`	TEXT,
	`word2`	TEXT,
	PRIMARY KEY(`word1`,`word2`)
);
INSERT INTO `word` VALUES ('impervious','impermeable');
INSERT INTO `word` VALUES ('impermeable','impervious');
INSERT INTO `word` VALUES ('impenetrable','impermeable');
INSERT INTO `word` VALUES ('impermeable','impenetrable');
INSERT INTO `word` VALUES ('impervious','impenetrable');
INSERT INTO `word` VALUES ('impenetrable','impervious');
INSERT INTO `word` VALUES ('inevitable','inescapable');
INSERT INTO `word` VALUES ('inescapable','inevitable');
INSERT INTO `word` VALUES ('unavoidable','inevitable');
INSERT INTO `word` VALUES ('inevitable','unavoidable');
INSERT INTO `word` VALUES ('inescapable','unavoidable');
INSERT INTO `word` VALUES ('unavoidable','inescapable');
INSERT INTO `word` VALUES ('contemptuous','scornful');
INSERT INTO `word` VALUES ('scornful','contemptuous');
INSERT INTO `word` VALUES ('disdainful','contemptuous');
INSERT INTO `word` VALUES ('contemptuous','disdainful');
INSERT INTO `word` VALUES ('scornful','disdainful');
INSERT INTO `word` VALUES ('disdainful','scornful');
INSERT INTO `word` VALUES ('disrespectful','contemptuous');
INSERT INTO `word` VALUES ('contemptuous','disrespectful');
INSERT INTO `word` VALUES ('disrespectful','scornful');
INSERT INTO `word` VALUES ('scornful','disrespectful');
INSERT INTO `word` VALUES ('disdainful','disrespectful');
INSERT INTO `word` VALUES ('disrespectful','disdainful');
INSERT INTO `word` VALUES ('insolent','rude');
INSERT INTO `word` VALUES ('rude','insolent');
INSERT INTO `word` VALUES ('impertinent','insolent');
INSERT INTO `word` VALUES ('insolent','impertinent');
INSERT INTO `word` VALUES ('impertinent','rude');
INSERT INTO `word` VALUES ('rude','impertinent');
INSERT INTO `word` VALUES ('devastating','destructive');
INSERT INTO `word` VALUES ('destructive','devastating');
INSERT INTO `word` VALUES ('ruinous','destructive');
INSERT INTO `word` VALUES ('destructive','ruinous');
INSERT INTO `word` VALUES ('ruinous','devastating');
INSERT INTO `word` VALUES ('devastating','ruinous');
INSERT INTO `word` VALUES ('extortionate','exorbitant');
INSERT INTO `word` VALUES ('exorbitant','extortionate');
INSERT INTO `word` VALUES ('equivocal','ambiguous');
INSERT INTO `word` VALUES ('ambiguous','equivocal');
INSERT INTO `word` VALUES ('transient','transitory');
INSERT INTO `word` VALUES ('transitory','transient');
INSERT INTO `word` VALUES ('temporary','transitory');
INSERT INTO `word` VALUES ('transitory','temporary');
INSERT INTO `word` VALUES ('transient','temporary');
INSERT INTO `word` VALUES ('temporary','transient');
INSERT INTO `word` VALUES ('ephemeral','temporary');
INSERT INTO `word` VALUES ('temporary','ephemeral');
INSERT INTO `word` VALUES ('ephemeral','transitory');
INSERT INTO `word` VALUES ('transitory','ephemeral');
INSERT INTO `word` VALUES ('transient','ephemeral');
INSERT INTO `word` VALUES ('ephemeral','transient');
INSERT INTO `word` VALUES ('indolent','slothful');
INSERT INTO `word` VALUES ('slothful','indolent');
INSERT INTO `word` VALUES ('lazy','indolent');
INSERT INTO `word` VALUES ('indolent','lazy');
INSERT INTO `word` VALUES ('lazy','slothful');
INSERT INTO `word` VALUES ('slothful','lazy');
INSERT INTO `word` VALUES ('avarice','greed');
INSERT INTO `word` VALUES ('greed','avarice');
COMMIT;
